local AutocephalyValueConfig = {
		["AutocephalyValueConfig"] = {["content"] = {
						[1] = {["Value"] = 100,["content"] = "HeroMaxLv",["Info"] = "英雄等级上限"},
						[2] = {["Value"] = 60,["content"] = "EatExp",["Info"] = "已吞噬过的装备被吞噬后经验总量百分比（%）"},
						[3] = {["Value"] = 10,["content"] = "smelt",["Info"] = "熔炼恢复的元宝（个）"},
						[4] = {["Value"] = 4,["content"] = "SceneEquipGainMax",["Info"] = "副本获得装备的上限（件）"},
						[5] = {["Value"] = 4,["content"] = "SceneGoldGainMax",["Info"] = "副本获得的金钱次数上限（次）"},
						[6] = {["Value"] = 3000,["content"] = "SkillChainCd",["Info"] = "技能链结束时的冷却时间（毫秒）"},
						[7] = {["Value"] = 3000,["content"] = "SkillSpacing",["Info"] = "技能链触发间隔，超过这个时间就进入CD（毫秒）"},
						[8] = {["Value"] = 1000,["content"] = "ComboSpacing",["Info"] = "连击数字断掉的间隔时间（毫秒）"},
						[9] = {["Value"] = 12,["content"] = "MagicSoulSceneMax",["Info"] = "器灵副本免费次数"},
						[10] = {["Value"] = 1900,["content"] = "ExpRatio",["Info"] = "首通经验比例(%)"},
						[11] = {["Value"] = 3512,["content"] = "GoldRatio",["Info"] = "首通主线本金币比例(%)"},
						[12] = {["Value"] = 60,["content"] = "SkillParameter",["Info"] = "技能链CD参数（%）"},
						[13] = {["Value"] = 100,["content"] = "MedicineRecovery",["Info"] = "血药恢复的血量（%）"},
						[14] = {["Value"] = 3,["content"] = "MedicineNumber",["Info"] = "血药的每一局的数量"},
						[15] = {["Value"] = 500,["content"] = "AlterName",["Info"] = "修改名字元宝消耗"},
						[16] = {["Value"] = 40,["content"] = "MoneyTime",["Info"] = "财神宝库结算倒计时（秒）"},
						[17] = {["Value"] = 0,["content"] = "EliteDropMin",["Info"] = "精英副本掉落件数最小值"},
						[18] = {["Value"] = 5,["content"] = "EliteDropMax",["Info"] = "精英副本掉落件数最大值"},
						[19] = {["Value"] = 5,["content"] = "EliteDropGold",["Info"] = "精英副本掉落钱的次数"},
						[20] = {["Value"] = 72,["content"] = "DeleteTime",["Info"] = "角色删除等待时间（时）"},
						[21] = {["Value"] = 3,["content"] = "TrainNumber",["Info"] = "试练塔进入次数"},
						[22] = {["Value"] = 4,["content"] = "TrainFreeTabletNumber",["Info"] = "试练塔免费翻牌张数"},
						[23] = {["Value"] = 4,["content"] = "TrainRmbTabletNumber",["Info"] = "试练塔付费翻牌张数"},
						[24] = {["Value"] = 4,["content"] = "MpAttack",["Info"] = "普通攻击回蓝（每次）"},
						[25] = {["Value"] = 4,["content"] = "MpSkill",["Info"] = "技能攻击回蓝（每次）"},
						[26] = {["Value"] = 4,["content"] = "MpHurt",["Info"] = "受击回蓝（每次）"},
						[27] = {["Value"] = 1,["content"] = "BoxMin",["Info"] = "宝箱掉落件数最小值"},
						[28] = {["Value"] = 3,["content"] = "BoxMax",["Info"] = "宝箱掉落件数最大值"},
						[29] = {["Value"] = 5,["content"] = "RefreshNum",["Info"] = "神将免费刷新次数"},
						[30] = {["Value"] = 12,["content"] = "ChallengeNum",["Info"] = "挑战次数上限"},
						[31] = {["Value"] = 5,["content"] = "RecruitMoneyNum",["Info"] = "招财初始次数上限"},
						[32] = {["Value"] = 1,["content"] = "PowerNum",["Info"] = "初始元力购买次数"},
						[33] = {["Value"] = 18,["content"] = "FightingForceSuppressOne",["Info"] = "战力压制参数1（百分比）"},
						[34] = {["Value"] = "0.1",["content"] = "FloatSlowDown",["Info"] = "减缓下降速度的比例"},
						[35] = {["Value"] = 1900,["content"] = "GoldRatioone",["Info"] = "精英本首通金币%"},
						[36] = {["Value"] = 1,["content"] = "GodPowerNum",["Info"] = "初始体力购买次数"},
						[37] = {["Value"] = 5,["content"] = "EquipRowNum",["Info"] = "装备系统背包横向"},
						[38] = {["Value"] = 60,["content"] = "EquipListNum",["Info"] = "装备系统背包竖向"},
						[39] = {["Value"] = 7,["content"] = "NewServer",["Info"] = "新服定义（开服时间天数）"},
						[40] = {["Value"] = 20,["content"] = "RushConsume",["Info"] = "突进消耗的破甲值"},
						[41] = {["Value"] = 86400,["content"] = "JoinTime",["Info"] = "再次加入仙门时间限制（秒）"},
						[42] = {["Value"] = 30,["content"] = "PkDeleteTime",["Info"] = "竞技场每日奖励删除时间（天）"},
						[43] = {["Value"] = 100,["content"] = "SociatyRmb",["Info"] = "创建仙门所需元宝"}
				}}
}
return AutocephalyValueConfig