local BulletConfig = {
		["BulletConfig"] = {["Bullet"] = {
						[1] = {["Interval"] = "0.2",["Ay"] = "0.5",["HitEffect"] = {["MoveType"] = 7,["Move_speedY"] = 0,["Move_Duration"] = "0.1",["Move_mGWhenUp"] = 0,["Move_mGWhenDown"] = 0,["Direction"] = 1,["Move_speedX"] = 500},["Height"] = 50,["Penetration"] = true,["Additive"] = true,["Ax"] = "0.5",["Res"] = "images/fireBall/huoqiu",["Width"] = 50,["SkillLv"] = {["Lv"] = 1,["DeblockingLv"] = 1,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 0,["AttrAddPercent"] = 60,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 10},["ActionName"] = "move",["HitBuffDataConfig"] = {["BuffData"] = {["FloatParam2"] = 1,["BuffId"] = 10001,["Duration"] = "0.25",["FloatParam1"] = 1}},["BulletId"] = 10001,["SkillHitEffect"] = {["HitEffect"] = {
												[1] = {["OffsetY"] = 0,["ArmorActionName"] = "hurt_5",["ActionName"] = "hurt_1",["Res"] = "images/hurtEffect/hurt_effect",["OffsetX"] = 0},
												[2] = {["OffsetY"] = 0,["ArmorActionName"] = "hurt_6",["ActionName"] = "hurt_2",["Res"] = "images/hurtEffect/hurt_effect",["OffsetX"] = 0},
												[3] = {["OffsetY"] = 0,["ArmorActionName"] = "hurt_7",["ActionName"] = "hurt_3",["Res"] = "images/hurtEffect/hurt_effect",["OffsetX"] = 0},
												[4] = {["OffsetY"] = 0,["ArmorActionName"] = "hurt_8",["ActionName"] = "hurt_4",["Res"] = "images/hurtEffect/hurt_effect",["OffsetX"] = 0}
										}},["SkillEffectEntityData"] = {["Additive"] = true,["ActionName"] = "attack_4",["Res"] = "",["Duration"] = 10}},
						[2] = {["Interval"] = "0.2",["HitEffect"] = {["MoveType"] = 7,["Move_speedY"] = 0,["Move_Duration"] = "0.1",["Move_mGWhenUp"] = 0,["Move_mGWhenDown"] = 0,["Direction"] = 1,["Move_speedX"] = 500},["Height"] = 50,["Penetration"] = false,["Additive"] = true,["Ax"] = "0.5",["Res"] = "images/fireBall/huoqiu",["SkillLv"] = {["Lv"] = 1,["DeblockingLv"] = 1,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 0,["AttrAddPercent"] = 60,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 10},["ActionName"] = "move",["HitBuffDataConfig"] = {["BuffData"] = {["FloatParam2"] = 1,["BuffId"] = 10001,["Duration"] = "0.25",["FloatParam1"] = 1}},["Ay"] = "0.5",["BulletId"] = 10002,["SkillHitEffect"] = {["HitEffect"] = {
												[1] = {["OffsetY"] = 0,["ArmorActionName"] = "hurt_5",["ActionName"] = "hurt_1",["Res"] = "images/hurtEffect/hurt_effect",["OffsetX"] = 0},
												[2] = {["OffsetY"] = 0,["ArmorActionName"] = "hurt_6",["ActionName"] = "hurt_2",["Res"] = "images/hurtEffect/hurt_effect",["OffsetX"] = 0},
												[3] = {["OffsetY"] = 0,["ArmorActionName"] = "hurt_7",["ActionName"] = "hurt_3",["Res"] = "images/hurtEffect/hurt_effect",["OffsetX"] = 0},
												[4] = {["OffsetY"] = 0,["ArmorActionName"] = "hurt_8",["ActionName"] = "hurt_4",["Res"] = "images/hurtEffect/hurt_effect",["OffsetX"] = 0}
										}},["Width"] = 50},
						[3] = {["Interval"] = "0.5",["Ay"] = "0.5",["HitEffect"] = {["MoveType"] = 7,["Move_speedY"] = 0,["Move_Duration"] = "0.1",["Move_mGWhenUp"] = 0,["Move_mGWhenDown"] = 0,["Direction"] = 1,["Move_speedX"] = 500},["Height"] = 50,["Penetration"] = true,["Additive"] = true,["Ax"] = "0.5",["Res"] = "images/heroeffect/huyao_effect",
								["SkillLv"] = {
										[1] = {["Lv"] = 1,["DeblockingLv"] = 7,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 13,["AttrAddPercent"] = 34.83,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 4000},
										[2] = {["Lv"] = 2,["DeblockingLv"] = 14,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 18,["AttrAddPercent"] = 35.67,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 8000},
										[3] = {["Lv"] = 3,["DeblockingLv"] = 17,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 23,["AttrAddPercent"] = 36.5,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 12000},
										[4] = {["Lv"] = 4,["DeblockingLv"] = 22,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 28,["AttrAddPercent"] = 37.33,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 16000},
										[5] = {["Lv"] = 5,["DeblockingLv"] = 26,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 33,["AttrAddPercent"] = 38.17,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 20000},
										[6] = {["Lv"] = 6,["DeblockingLv"] = 29,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 38,["AttrAddPercent"] = 39,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 24000},
										[7] = {["Lv"] = 7,["DeblockingLv"] = 34,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 43,["AttrAddPercent"] = 39.83,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 28000},
										[8] = {["Lv"] = 8,["DeblockingLv"] = 39,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 48,["AttrAddPercent"] = 40.67,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 32000},
										[9] = {["Lv"] = 9,["DeblockingLv"] = 44,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 53,["AttrAddPercent"] = 41.5,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 36000},
										[10] = {["Lv"] = 10,["DeblockingLv"] = 49,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 58,["AttrAddPercent"] = 42.33,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 40000},
										[11] = {["Lv"] = 11,["DeblockingLv"] = 54,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 63,["AttrAddPercent"] = 43.17,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 44000},
										[12] = {["Lv"] = 12,["DeblockingLv"] = 59,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 68,["AttrAddPercent"] = 44,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 48000},
										[13] = {["Lv"] = 13,["DeblockingLv"] = 64,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 73,["AttrAddPercent"] = 44.83,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 52000},
										[14] = {["Lv"] = 14,["DeblockingLv"] = 69,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 78,["AttrAddPercent"] = 45.67,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 56000},
										[15] = {["Lv"] = 15,["DeblockingLv"] = 74,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 83,["AttrAddPercent"] = 46.5,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 60000},
										[16] = {["Lv"] = 16,["DeblockingLv"] = 79,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 88,["AttrAddPercent"] = 47.33,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 64000},
										[17] = {["Lv"] = 17,["DeblockingLv"] = 84,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 93,["AttrAddPercent"] = 48.17,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 68000},
										[18] = {["Lv"] = 18,["DeblockingLv"] = 89,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 98,["AttrAddPercent"] = 49,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 72000},
										[19] = {["Lv"] = 19,["DeblockingLv"] = 94,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 103,["AttrAddPercent"] = 49.83,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 76000},
										[20] = {["Lv"] = 20,["DeblockingLv"] = 99,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 108,["AttrAddPercent"] = 50.67,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 80000}
								},
								["ActionName"] = "skill_302",["HitBuffDataConfig"] = {["BuffData"] = {["FloatParam2"] = 1,["BuffId"] = 10001,["Duration"] = "0.25",["FloatParam1"] = 1}},["SkillEntityConfig"] = 0,["BulletId"] = 102071,["SkillHitEffect"] = {["HitEffect"] = {
												[1] = {["OffsetY"] = 0,["ArmorActionName"] = "hurt_5",["ActionName"] = "hurt_1",["Res"] = "images/hurtEffect/hurt_effect",["OffsetX"] = 0},
												[2] = {["OffsetY"] = 0,["ArmorActionName"] = "hurt_6",["ActionName"] = "hurt_2",["Res"] = "images/hurtEffect/hurt_effect",["OffsetX"] = 0},
												[3] = {["OffsetY"] = 0,["ArmorActionName"] = "hurt_7",["ActionName"] = "hurt_3",["Res"] = "images/hurtEffect/hurt_effect",["OffsetX"] = 0},
												[4] = {["OffsetY"] = 0,["ArmorActionName"] = "hurt_8",["ActionName"] = "hurt_4",["Res"] = "images/hurtEffect/hurt_effect",["OffsetX"] = 0}
										}},["Width"] = 50},
						[4] = {["Interval"] = "0.1",["Ay"] = "0.5",["HitEffect"] = {["MoveType"] = 7,["Move_speedY"] = 0,["Move_Duration"] = "0.1",["Move_mGWhenUp"] = 0,["Move_mGWhenDown"] = 0,["Direction"] = 1,["Move_speedX"] = 600},["Height"] = 100,["Penetration"] = true,["Additive"] = true,["Ax"] = "0.5",["Res"] = "images/heroeffect/huyao_effect",["Width"] = 100,
								["SkillLv"] = {
										[1] = {["Lv"] = 1,["DeblockingLv"] = 7,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 13,["AttrAddPercent"] = 34.83,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 4000},
										[2] = {["Lv"] = 2,["DeblockingLv"] = 14,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 18,["AttrAddPercent"] = 35.67,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 8000},
										[3] = {["Lv"] = 3,["DeblockingLv"] = 17,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 23,["AttrAddPercent"] = 36.5,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 12000},
										[4] = {["Lv"] = 4,["DeblockingLv"] = 22,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 28,["AttrAddPercent"] = 37.33,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 16000},
										[5] = {["Lv"] = 5,["DeblockingLv"] = 26,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 33,["AttrAddPercent"] = 38.17,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 20000},
										[6] = {["Lv"] = 6,["DeblockingLv"] = 29,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 38,["AttrAddPercent"] = 39,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 24000},
										[7] = {["Lv"] = 7,["DeblockingLv"] = 34,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 43,["AttrAddPercent"] = 39.83,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 28000},
										[8] = {["Lv"] = 8,["DeblockingLv"] = 39,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 48,["AttrAddPercent"] = 40.67,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 32000},
										[9] = {["Lv"] = 9,["DeblockingLv"] = 44,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 53,["AttrAddPercent"] = 41.5,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 36000},
										[10] = {["Lv"] = 10,["DeblockingLv"] = 49,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 58,["AttrAddPercent"] = 42.33,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 40000},
										[11] = {["Lv"] = 11,["DeblockingLv"] = 54,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 63,["AttrAddPercent"] = 43.17,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 44000},
										[12] = {["Lv"] = 12,["DeblockingLv"] = 59,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 68,["AttrAddPercent"] = 44,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 48000},
										[13] = {["Lv"] = 13,["DeblockingLv"] = 64,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 73,["AttrAddPercent"] = 44.83,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 52000},
										[14] = {["Lv"] = 14,["DeblockingLv"] = 69,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 78,["AttrAddPercent"] = 45.67,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 56000},
										[15] = {["Lv"] = 15,["DeblockingLv"] = 74,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 83,["AttrAddPercent"] = 46.5,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 60000},
										[16] = {["Lv"] = 16,["DeblockingLv"] = 79,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 88,["AttrAddPercent"] = 47.33,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 64000},
										[17] = {["Lv"] = 17,["DeblockingLv"] = 84,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 93,["AttrAddPercent"] = 48.17,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 68000},
										[18] = {["Lv"] = 18,["DeblockingLv"] = 89,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 98,["AttrAddPercent"] = 49,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 72000},
										[19] = {["Lv"] = 19,["DeblockingLv"] = 94,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 103,["AttrAddPercent"] = 49.83,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 76000},
										[20] = {["Lv"] = 20,["DeblockingLv"] = 99,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 108,["AttrAddPercent"] = 50.67,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 80000}
								},
								["ActionName"] = "skill_402",["HitBuffDataConfig"] = {["BuffData"] = {["FloatParam2"] = 1,["BuffId"] = 10001,["Duration"] = "0.25",["FloatParam1"] = 1}},["SkillEntityConfig"] = {["SkillEntity"] = {
												[1] = {["OffsetY"] = 0,["SkillId"] = 102082,["OffsetX"] = 0,["StartTime"] = 0,["Additive"] = true,["Direction"] = 1,["Res"] = "images/heroeffect/huyao_effect",["Duration"] = "0.5"},
												[2] = {["OffsetY"] = 0,["SkillId"] = 102083,["OffsetX"] = 0,["StartTime"] = 0,["Additive"] = false,["Direction"] = 1,["Res"] = "images/heroeffect/huyao_effect",["Duration"] = "0.5"}
										}},["BulletId"] = 102081,["SkillHitEffect"] = {["HitEffect"] = {
												[1] = {["OffsetY"] = 0,["ArmorActionName"] = "hurt_5",["ActionName"] = "hurt_1",["Res"] = "images/hurtEffect/hurt_effect",["OffsetX"] = 0},
												[2] = {["OffsetY"] = 0,["ArmorActionName"] = "hurt_6",["ActionName"] = "hurt_2",["Res"] = "images/hurtEffect/hurt_effect",["OffsetX"] = 0},
												[3] = {["OffsetY"] = 0,["ArmorActionName"] = "hurt_7",["ActionName"] = "hurt_3",["Res"] = "images/hurtEffect/hurt_effect",["OffsetX"] = 0},
												[4] = {["OffsetY"] = 0,["ArmorActionName"] = "hurt_8",["ActionName"] = "hurt_4",["Res"] = "images/hurtEffect/hurt_effect",["OffsetX"] = 0}
										}},["SkillEffectEntityData"] = {["Additive"] = true,["ActionName"] = "attack_4",["Res"] = "",["Duration"] = 10}},
						[5] = {["Interval"] = -1,["Ay"] = "0.5",["Height"] = 100,["Penetration"] = true,["Additive"] = true,["Ax"] = "0.5",["Res"] = "images/heroeffect/huyao_effect",["Width"] = 100,
								["SkillLv"] = {
										[1] = {["Lv"] = 1,["DeblockingLv"] = 23,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 13,["AttrAddPercent"] = 34.5,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 4000},
										[2] = {["Lv"] = 2,["DeblockingLv"] = 27,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 23,["AttrAddPercent"] = 36.17,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 8000},
										[3] = {["Lv"] = 3,["DeblockingLv"] = 30,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 33,["AttrAddPercent"] = 37.83,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 12000},
										[4] = {["Lv"] = 4,["DeblockingLv"] = 34,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 43,["AttrAddPercent"] = 39.5,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 16000},
										[5] = {["Lv"] = 5,["DeblockingLv"] = 38,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 53,["AttrAddPercent"] = 41.17,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 20000},
										[6] = {["Lv"] = 6,["DeblockingLv"] = 42,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 63,["AttrAddPercent"] = 42.83,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 24000},
										[7] = {["Lv"] = 7,["DeblockingLv"] = 46,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 73,["AttrAddPercent"] = 44.5,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 28000},
										[8] = {["Lv"] = 8,["DeblockingLv"] = 50,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 83,["AttrAddPercent"] = 46.17,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 32000},
										[9] = {["Lv"] = 9,["DeblockingLv"] = 54,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 93,["AttrAddPercent"] = 47.83,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 36000},
										[10] = {["Lv"] = 10,["DeblockingLv"] = 58,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 103,["AttrAddPercent"] = 49.5,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 40000},
										[11] = {["Lv"] = 11,["DeblockingLv"] = 62,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 113,["AttrAddPercent"] = 51.17,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 44000},
										[12] = {["Lv"] = 12,["DeblockingLv"] = 66,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 123,["AttrAddPercent"] = 52.83,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 48000},
										[13] = {["Lv"] = 13,["DeblockingLv"] = 70,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 133,["AttrAddPercent"] = 54.5,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 52000},
										[14] = {["Lv"] = 14,["DeblockingLv"] = 74,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 143,["AttrAddPercent"] = 56.17,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 56000},
										[15] = {["Lv"] = 15,["DeblockingLv"] = 78,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 153,["AttrAddPercent"] = 57.83,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 60000},
										[16] = {["Lv"] = 16,["DeblockingLv"] = 82,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 163,["AttrAddPercent"] = 59.5,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 64000},
										[17] = {["Lv"] = 17,["DeblockingLv"] = 86,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 173,["AttrAddPercent"] = 61.17,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 68000},
										[18] = {["Lv"] = 18,["DeblockingLv"] = 90,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 183,["AttrAddPercent"] = 62.83,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 72000},
										[19] = {["Lv"] = 19,["DeblockingLv"] = 94,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 193,["AttrAddPercent"] = 64.5,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 76000},
										[20] = {["Lv"] = 20,["DeblockingLv"] = 98,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 203,["AttrAddPercent"] = 66.17,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 80000}
								},
								["ActionName"] = "skill_302",["HitBuffDataConfig"] = {["BuffData"] = {["FloatParam2"] = 1,["BuffId"] = 10001,["Duration"] = "0.25",["FloatParam1"] = 1}},["SkillEntityConfig"] = {["SkillEntity"] = {
												[1] = {["OffsetY"] = 0,["SkillId"] = 102093,["OffsetX"] = 0,["StartTime"] = 0,["Additive"] = false,["Direction"] = 1,["Res"] = "images/heroeffect/huyao_effect",["Duration"] = "0.1"},
												[2] = {["OffsetY"] = 0,["SkillId"] = 102092,["OffsetX"] = 0,["StartTime"] = 0,["Additive"] = true,["Direction"] = 1,["Res"] = "images/heroeffect/huyao_effect",["Duration"] = "0.1"}
										}},["BulletId"] = 102091,["SkillHitEffect"] = {["HitEffect"] = {
												[1] = {["OffsetY"] = 0,["ArmorActionName"] = "hurt_5",["ActionName"] = "hurt_1",["Res"] = "images/hurtEffect/hurt_effect",["OffsetX"] = 0},
												[2] = {["OffsetY"] = 0,["ArmorActionName"] = "hurt_6",["ActionName"] = "hurt_2",["Res"] = "images/hurtEffect/hurt_effect",["OffsetX"] = 0},
												[3] = {["OffsetY"] = 0,["ArmorActionName"] = "hurt_7",["ActionName"] = "hurt_3",["Res"] = "images/hurtEffect/hurt_effect",["OffsetX"] = 0},
												[4] = {["OffsetY"] = 0,["ArmorActionName"] = "hurt_8",["ActionName"] = "hurt_4",["Res"] = "images/hurtEffect/hurt_effect",["OffsetX"] = 0}
										}},["SkillEffectEntityData"] = {["Additive"] = true,["ActionName"] = "attack_4",["Res"] = "",["Duration"] = 10}},
						[6] = {["Interval"] = -1,["Height"] = 80,["Penetration"] = false,["Additive"] = false,["Ax"] = "0.5",["Res"] = "images/monstereffect/kulousheshou_effect",["Width"] = 100,["SkillLv"] = {["Lv"] = 1,["DeblockingLv"] = 1,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 0,["AttrAddPercent"] = 60,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 10},["ActionName"] = "attack_1",["HitBuffDataConfig"] = {["BuffData"] = {["FloatParam2"] = 1,["BuffId"] = 10001,["Duration"] = "0.25",["FloatParam1"] = 1}},["Ay"] = "0.5",["BulletId"] = 216011,["SkillHitEffect"] = {["HitEffect"] = {
												[1] = {["OffsetY"] = 0,["ArmorActionName"] = "hurt_5",["ActionName"] = "hurt_1",["Res"] = "images/hurtEffect/hurt_effect",["OffsetX"] = 0},
												[2] = {["OffsetY"] = 0,["ArmorActionName"] = "hurt_6",["ActionName"] = "hurt_2",["Res"] = "images/hurtEffect/hurt_effect",["OffsetX"] = 0},
												[3] = {["OffsetY"] = 0,["ArmorActionName"] = "hurt_7",["ActionName"] = "hurt_3",["Res"] = "images/hurtEffect/hurt_effect",["OffsetX"] = 0},
												[4] = {["OffsetY"] = 0,["ArmorActionName"] = "hurt_8",["ActionName"] = "hurt_4",["Res"] = "images/hurtEffect/hurt_effect",["OffsetX"] = 0}
										}},["SkillEffectEntityData"] = {["Additive"] = true,["ActionName"] = "attack_4",["Res"] = "",["Duration"] = 10}},
						[7] = {["Interval"] = "0.15",["Height"] = 200,["Penetration"] = true,["Additive"] = true,["Ax"] = "0.5",["Res"] = "images/bosseffect/zhenyuandaxian_effect",["SkillLv"] = {["Lv"] = 1,["DeblockingLv"] = 1,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 0,["AttrAddPercent"] = 60,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 10},["ActionName"] = "attack_1_2",["HitBuffDataConfig"] = {["BuffData"] = {["FloatParam2"] = 1,["BuffId"] = 10001,["Duration"] = "0.25",["FloatParam1"] = 1}},["Ay"] = "0.5",["BulletId"] = 306011,["SkillHitEffect"] = {["HitEffect"] = {
												[1] = {["OffsetY"] = 0,["ArmorActionName"] = "hurt_5",["ActionName"] = "hurt_1",["Res"] = "images/hurtEffect/hurt_effect",["OffsetX"] = 0},
												[2] = {["OffsetY"] = 0,["ArmorActionName"] = "hurt_6",["ActionName"] = "hurt_2",["Res"] = "images/hurtEffect/hurt_effect",["OffsetX"] = 0},
												[3] = {["OffsetY"] = 0,["ArmorActionName"] = "hurt_7",["ActionName"] = "hurt_3",["Res"] = "images/hurtEffect/hurt_effect",["OffsetX"] = 0},
												[4] = {["OffsetY"] = 0,["ArmorActionName"] = "hurt_8",["ActionName"] = "hurt_4",["Res"] = "images/hurtEffect/hurt_effect",["OffsetX"] = 0}
										}},["Width"] = 150},
						[8] = {["Interval"] = "0.15",["Ay"] = "0.5",["Height"] = 50,["Penetration"] = false,["Additive"] = true,["Ax"] = "0.5",["Res"] = "images/bosseffect/jinjiao_effect",["SkillLv"] = {["Lv"] = 1,["DeblockingLv"] = 1,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 0,["AttrAddPercent"] = 60,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 10},["ActionName"] = "attack_302",["HitBuffDataConfig"] = {["BuffData"] = {["FloatParam2"] = 1,["BuffId"] = 10001,["Duration"] = "0.25",["FloatParam1"] = 1}},["SkillEntityConfig"] = {["SkillEntity"] = {["OffsetY"] = -230,["SkillId"] = 309032,["OffsetX"] = 0,["StartTime"] = 0,["Additive"] = true,["Direction"] = 1,["Res"] = "images/bosseffect/jinjiao_effect",["Duration"] = "0.1"}},["BulletId"] = 309031,["SkillHitEffect"] = {["HitEffect"] = {
												[1] = {["OffsetY"] = 0,["ArmorActionName"] = "hurt_5",["ActionName"] = "hurt_1",["Res"] = "images/hurtEffect/hurt_effect",["OffsetX"] = 0},
												[2] = {["OffsetY"] = 0,["ArmorActionName"] = "hurt_6",["ActionName"] = "hurt_2",["Res"] = "images/hurtEffect/hurt_effect",["OffsetX"] = 0},
												[3] = {["OffsetY"] = 0,["ArmorActionName"] = "hurt_7",["ActionName"] = "hurt_3",["Res"] = "images/hurtEffect/hurt_effect",["OffsetX"] = 0},
												[4] = {["OffsetY"] = 0,["ArmorActionName"] = "hurt_8",["ActionName"] = "hurt_4",["Res"] = "images/hurtEffect/hurt_effect",["OffsetX"] = 0}
										}},["Width"] = 20},
						[9] = {["Interval"] = "0.15",["Height"] = 50,["Penetration"] = true,["Additive"] = true,["Ax"] = "0.5",["Res"] = "images/bosseffect/jiaguowang_effect",["SkillLv"] = {["Lv"] = 1,["DeblockingLv"] = 1,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 0,["AttrAddPercent"] = 60,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 10},["ActionName"] = "attack_1",["HitBuffDataConfig"] = {["BuffData"] = {["FloatParam2"] = 1,["BuffId"] = 10001,["Duration"] = "0.25",["FloatParam1"] = 1}},["Ay"] = "0.5",["BulletId"] = 311011,["SkillHitEffect"] = {["HitEffect"] = {
												[1] = {["OffsetY"] = 0,["ArmorActionName"] = "hurt_5",["ActionName"] = "hurt_1",["Res"] = "images/hurtEffect/hurt_effect",["OffsetX"] = 0},
												[2] = {["OffsetY"] = 0,["ArmorActionName"] = "hurt_6",["ActionName"] = "hurt_2",["Res"] = "images/hurtEffect/hurt_effect",["OffsetX"] = 0},
												[3] = {["OffsetY"] = 0,["ArmorActionName"] = "hurt_7",["ActionName"] = "hurt_3",["Res"] = "images/hurtEffect/hurt_effect",["OffsetX"] = 0},
												[4] = {["OffsetY"] = 0,["ArmorActionName"] = "hurt_8",["ActionName"] = "hurt_4",["Res"] = "images/hurtEffect/hurt_effect",["OffsetX"] = 0}
										}},["Width"] = 20},
						[10] = {["Interval"] = "0.1",["HitEffect"] = {["MoveType"] = 7,["Move_speedY"] = 0,["Move_Duration"] = "0.1",["Move_mGWhenUp"] = 0,["Move_mGWhenDown"] = 0,["Direction"] = 1,["Move_speedX"] = 600},["Height"] = 300,["Penetration"] = true,["Additive"] = true,["Ax"] = 0,["Res"] = "images/YuanShenSkill/fashijian",["SkillLv"] = {["Lv"] = 1,["DeblockingLv"] = 1,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 0,["AttrAddPercent"] = 60,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 10},["ActionName"] = "ready",["HitBuffDataConfig"] = {["BuffData"] = {["FloatParam2"] = 1,["BuffId"] = 10001,["Duration"] = "0.25",["FloatParam1"] = 1}},["Ay"] = "0.5",["BulletId"] = 405011,["SkillHitEffect"] = {["HitEffect"] = {
												[1] = {["OffsetY"] = 0,["ArmorActionName"] = "hurt_5",["ActionName"] = "hurt_1",["Res"] = "images/hurtEffect/hurt_effect",["OffsetX"] = 0},
												[2] = {["OffsetY"] = 0,["ArmorActionName"] = "hurt_6",["ActionName"] = "hurt_2",["Res"] = "images/hurtEffect/hurt_effect",["OffsetX"] = 0},
												[3] = {["OffsetY"] = 0,["ArmorActionName"] = "hurt_7",["ActionName"] = "hurt_3",["Res"] = "images/hurtEffect/hurt_effect",["OffsetX"] = 0},
												[4] = {["OffsetY"] = 0,["ArmorActionName"] = "hurt_8",["ActionName"] = "hurt_4",["Res"] = "images/hurtEffect/hurt_effect",["OffsetX"] = 0}
										}},["Width"] = 300},
						[11] = {["Interval"] = 1,["Height"] = 300,["Penetration"] = true,["Additive"] = true,["Ax"] = 0,["Res"] = "images/MagicSoulSkill/feijian",["SkillLv"] = {["Lv"] = 1,["DeblockingLv"] = 1,["DeblockingRmb"] = 0,["SkillValue"] = {["ChangeAttr"] = 1,["Time"] = 0,["TargetType"] = 2,["PerSecond"] = 0,["ChangeType"] = 1,["AttrAddType"] = 1,["BaseValue"] = 0,["AttrAddPercent"] = 60,["AttrAddTarget"] = 1,["DamageType"] = 1},["DeblockingGold"] = 10},["ActionName"] = "ready",["HitBuffDataConfig"] = {["BuffData"] = {["FloatParam2"] = 1,["BuffId"] = 10001,["Duration"] = "0.25",["FloatParam1"] = 1}},["Ay"] = "0.5",["BulletId"] = 501011,["SkillHitEffect"] = {["HitEffect"] = {
												[1] = {["OffsetY"] = 0,["ArmorActionName"] = "hurt_5",["ActionName"] = "hurt_1",["Res"] = "images/hurtEffect/hurt_effect",["OffsetX"] = 0},
												[2] = {["OffsetY"] = 0,["ArmorActionName"] = "hurt_6",["ActionName"] = "hurt_2",["Res"] = "images/hurtEffect/hurt_effect",["OffsetX"] = 0},
												[3] = {["OffsetY"] = 0,["ArmorActionName"] = "hurt_7",["ActionName"] = "hurt_3",["Res"] = "images/hurtEffect/hurt_effect",["OffsetX"] = 0},
												[4] = {["OffsetY"] = 0,["ArmorActionName"] = "hurt_8",["ActionName"] = "hurt_4",["Res"] = "images/hurtEffect/hurt_effect",["OffsetX"] = 0}
										}},["Width"] = 300}
				}}
}
return BulletConfig