luacf = {}
local OssatureConfig = require("src.lua_config.OssatureConfig")
luacf.Ossature=OssatureConfig
local StarAppraiseConfig = require("src.lua_config.StarAppraiseConfig")
luacf.StarAppraise=StarAppraiseConfig
local AutocephalyValueConfig = require("src.lua_config.AutocephalyValueConfig")
luacf.AutocephalyValue=AutocephalyValueConfig
local InitialConfig = require("src.lua_config.InitialConfig")
luacf.Initial=InitialConfig
local GuideSceneConfig = require("src.lua_config.GuideSceneConfig")
luacf.GuideScene=GuideSceneConfig
local EquipBaseConfig = require("src.lua_config.EquipBaseConfig")
luacf.EquipBase=EquipBaseConfig
local AIBehaviorTree = require("src.lua_config.AIBehaviorTree")
luacf.AIBehaviorTree=AIBehaviorTree
local ActivityConfig = require("src.lua_config.ActivityConfig")
luacf.Activity=ActivityConfig
local PowerConfig = require("src.lua_config.PowerConfig")
luacf.Power=PowerConfig
local SkillAnimationConfig = require("src.lua_config.SkillAnimationConfig")
luacf.SkillAnimation=SkillAnimationConfig
local GodGeneralsConfig = require("src.lua_config.GodGeneralsConfig")
luacf.GodGenerals=GodGeneralsConfig
local SkillConfig = require("src.lua_config.SkillConfig")
luacf.Skill=SkillConfig
local SociatyWarMsgConfig = require("src.lua_config.SociatyWarMsgConfig")
luacf.SociatyWarMsg=SociatyWarMsgConfig
local MagicSoulSceneConfig = require("src.lua_config.MagicSoulSceneConfig")
luacf.MagicSoulScene=MagicSoulSceneConfig
local SociatyWarTileDefineConfig = require("src.lua_config.SociatyWarTileDefineConfig")
luacf.SociatyWarTileDefine=SociatyWarTileDefineConfig
local CopyConfig = require("src.lua_config.CopyConfig")
luacf.Copy=CopyConfig
local HeroConfig = require("src.lua_config.HeroConfig")
luacf.Hero=HeroConfig
local FunctionOpenConfig = require("src.lua_config.FunctionOpenConfig")
luacf.FunctionOpen=FunctionOpenConfig
local NewFunctionConfig = require("src.lua_config.NewFunctionConfig")
luacf.NewFunction=NewFunctionConfig
local StarRewardConfig = require("src.lua_config.StarRewardConfig")
luacf.StarReward=StarRewardConfig
local MonsterGroupConfig = require("src.lua_config.MonsterGroupConfig")
luacf.MonsterGroup=MonsterGroupConfig
local HelperConfig = require("src.lua_config.HelperConfig")
luacf.Helper=HelperConfig
local HeroBaseAttrConfig = require("src.lua_config.HeroBaseAttrConfig")
luacf.HeroBaseAttr=HeroBaseAttrConfig
local ArmorConfig = require("src.lua_config.ArmorConfig")
luacf.Armor=ArmorConfig
local SceneRewardConfig = require("src.lua_config.SceneRewardConfig")
luacf.SceneReward=SceneRewardConfig
local SkyPagodaConfig = require("src.lua_config.SkyPagodaConfig")
luacf.SkyPagoda=SkyPagodaConfig
local EquipStrengthenConfig = require("src.lua_config.EquipStrengthenConfig")
luacf.EquipStrengthen=EquipStrengthenConfig
local VipConfig = require("src.lua_config.VipConfig")
luacf.Vip=VipConfig
local SociatyWarTiledMapConfig = require("src.lua_config.SociatyWarTiledMapConfig")
luacf.SociatyWarTiledMap=SociatyWarTiledMapConfig
local ArenaConfig = require("src.lua_config.ArenaConfig")
luacf.Arena=ArenaConfig
local PrayConfig = require("src.lua_config.PrayConfig")
luacf.Pray=PrayConfig
local SociatyWarMonsterDropConfig = require("src.lua_config.SociatyWarMonsterDropConfig")
luacf.SociatyWarMonsterDrop=SociatyWarMonsterDropConfig
local TaskConfig = require("src.lua_config.TaskConfig")
luacf.Task=TaskConfig
local GoodsConfig = require("src.lua_config.GoodsConfig")
luacf.Goods=GoodsConfig
local ReviveConfig = require("src.lua_config.ReviveConfig")
luacf.Revive=ReviveConfig
local VipNoteConfig = require("src.lua_config.VipNoteConfig")
luacf.VipNote=VipNoteConfig
local FirstPayConfig = require("src.lua_config.FirstPayConfig")
luacf.FirstPay=FirstPayConfig
local StoryTalkConfig = require("src.lua_config.StoryTalkConfig")
luacf.StoryTalk=StoryTalkConfig
local RecruitMoneyConfig = require("src.lua_config.RecruitMoneyConfig")
luacf.RecruitMoney=RecruitMoneyConfig
local ScenesConfig = require("src.lua_config.ScenesConfig")
luacf.Scenes=ScenesConfig
local ObstacleConfig = require("src.lua_config.ObstacleConfig")
luacf.Obstacle=ObstacleConfig
local TrainConfig = require("src.lua_config.TrainConfig")
luacf.Train=TrainConfig
local GodGeneralsSceneConfig = require("src.lua_config.GodGeneralsSceneConfig")
luacf.GodGeneralsScene=GodGeneralsSceneConfig
local TreasuryConfig = require("src.lua_config.TreasuryConfig")
luacf.Treasury=TreasuryConfig
local YuanshenConfig = require("src.lua_config.YuanshenConfig")
luacf.Yuanshen=YuanshenConfig
local SkillChainConfig = require("src.lua_config.SkillChainConfig")
luacf.SkillChain=SkillChainConfig
local ChapterConfig = require("src.lua_config.ChapterConfig")
luacf.Chapter=ChapterConfig
local MagicSoulConfig = require("src.lua_config.MagicSoulConfig")
luacf.MagicSoul=MagicSoulConfig
local CopyWinReward = require("src.lua_config.CopyWinReward")
luacf.CopyWinReward=CopyWinReward
local GuideConfig = require("src.lua_config.GuideConfig")
luacf.Guide=GuideConfig
local SociatyJobConfig = require("src.lua_config.SociatyJobConfig")
luacf.SociatyJob=SociatyJobConfig
local MonsterBaseAttrConfig = require("src.lua_config.MonsterBaseAttrConfig")
luacf.MonsterBaseAttr=MonsterBaseAttrConfig
local MagicSoulSkillConfig = require("src.lua_config.MagicSoulSkillConfig")
luacf.MagicSoulSkill=MagicSoulSkillConfig
local SociatyEventConfig = require("src.lua_config.SociatyEventConfig")
luacf.SociatyEvent=SociatyEventConfig
local SociatyWarBaseResConfig = require("src.lua_config.SociatyWarBaseResConfig")
luacf.SociatyWarBaseRes=SociatyWarBaseResConfig
local HeroSkillConfig = require("src.lua_config.HeroSkillConfig")
luacf.HeroSkill=HeroSkillConfig
local FemaleCelestialSkillConfig = require("src.lua_config.FemaleCelestialSkillConfig")
luacf.FemaleCelestialSkill=FemaleCelestialSkillConfig
local PeentoConfig = require("src.lua_config.PeentoConfig")
luacf.Peento=PeentoConfig
local SensitiveConfig = require("src.lua_config.SensitiveConfig")
luacf.Sensitive=SensitiveConfig
local MoveNewsConfig = require("src.lua_config.MoveNewsConfig")
luacf.MoveNews=MoveNewsConfig
local TalentConfig = require("src.lua_config.TalentConfig")
luacf.Talent=TalentConfig
local ExchangeConfig = require("src.lua_config.ExchangeConfig")
luacf.Exchange=ExchangeConfig
local EquipQualityConfig = require("src.lua_config.EquipQualityConfig")
luacf.EquipQuality=EquipQualityConfig
local FemaleCelestialConfig = require("src.lua_config.FemaleCelestialConfig")
luacf.FemaleCelestial=FemaleCelestialConfig
local WorldBossConfig = require("src.lua_config.WorldBossConfig")
luacf.WorldBoss=WorldBossConfig
local SociatyWarBaseConfig = require("src.lua_config.SociatyWarBaseConfig")
luacf.SociatyWarBase=SociatyWarBaseConfig
local RechargeConfig = require("src.lua_config.RechargeConfig")
luacf.Recharge=RechargeConfig
local SociatyLvConfig = require("src.lua_config.SociatyLvConfig")
luacf.SociatyLv=SociatyLvConfig
local MpConfig = require("src.lua_config.MpConfig")
luacf.Mp=MpConfig
local AttrControlConfig = require("src.lua_config.AttrControlConfig")
luacf.AttrControl=AttrControlConfig
local TipsConfig = require("src.lua_config.TipsConfig")
luacf.Tips=TipsConfig
local MoneySceneConfig = require("src.lua_config.MoneySceneConfig")
luacf.MoneyScene=MoneySceneConfig
local MonsterConfig = require("src.lua_config.MonsterConfig")
luacf.Monster=MonsterConfig
local NameConfig = require("src.lua_config.NameConfig")
luacf.Name=NameConfig
local PkConfig = require("src.lua_config.PkConfig")
luacf.Pk=PkConfig
local SociatyWarFactionResConfig = require("src.lua_config.SociatyWarFactionResConfig")
luacf.SociatyWarFactionRes=SociatyWarFactionResConfig
local BulletConfig = require("src.lua_config.BulletConfig")
luacf.Bullet=BulletConfig
