local VipConfig = {
		["VipConfig"] = {["Demand"] = {["Rate"] = {["Rate"] = 200},
						["VipDemand"] = {
								[1] = {["Rmb"] = 0,["Lv"] = 1},
								[2] = {["Rmb"] = 0,["Lv"] = 2},
								[3] = {["Rmb"] = 0,["Lv"] = 3},
								[4] = {["Rmb"] = 0,["Lv"] = 4},
								[5] = {["Rmb"] = 6,["Lv"] = 5},
								[6] = {["Rmb"] = 50,["Lv"] = 6},
								[7] = {["Rmb"] = 120,["Lv"] = 7},
								[8] = {["Rmb"] = 480,["Lv"] = 8},
								[9] = {["Rmb"] = 800,["Lv"] = 9},
								[10] = {["Rmb"] = 1200,["Lv"] = 10},
								[11] = {["Rmb"] = 1500,["Lv"] = 11},
								[12] = {["Rmb"] = 2000,["Lv"] = 12},
								[13] = {["Rmb"] = 2500,["Lv"] = 13},
								[14] = {["Rmb"] = 3000,["Lv"] = 14},
								[15] = {["Rmb"] = 4000,["Lv"] = 15}
						}},
				["Privilege"] = {["VipPrivilege"] = {
								[1] = {["function"] = {
												[1] = {["Parameter2"] = 0,["Parameter1"] = 0,["Type"] = 13},
												[2] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 16},
												[3] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 19},
												[4] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 29},
												[5] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 28}
										},
										["Lv"] = 0,
										["appreciation"] = {
												[1] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 26},
												[2] = {["Parameter2"] = 0,["Parameter1"] = 5,["Type"] = 14},
												[3] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 6},
												[4] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 7},
												[5] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 8},
												[6] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 9},
												[7] = {["Parameter2"] = 0,["Parameter1"] = 5,["Type"] = 27},
												[8] = {["Parameter2"] = 0,["Parameter1"] = 5,["Type"] = 30}
										}},
								[2] = {["function"] = {
												[1] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 13},
												[2] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 16},
												[3] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 28},
												[4] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 29},
												[5] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 19}
										},
										["Lv"] = 1,
										["appreciation"] = {
												[1] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 6},
												[2] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 7},
												[3] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 8},
												[4] = {["Parameter2"] = 0,["Parameter1"] = 2,["Type"] = 9},
												[5] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 10},
												[6] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 11},
												[7] = {["Parameter2"] = 0,["Parameter1"] = 5,["Type"] = 12},
												[8] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 22},
												[9] = {["Parameter2"] = 0,["Parameter1"] = 6,["Type"] = 14},
												[10] = {["Parameter2"] = 0,["Parameter1"] = 3,["Type"] = 26},
												[11] = {["Parameter2"] = 0,["Parameter1"] = 6,["Type"] = 30},
												[12] = {["Parameter2"] = 0,["Parameter1"] = 6,["Type"] = 27}
										}},
								[3] = {["function"] = {
												[1] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 13},
												[2] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 16},
												[3] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 19},
												[4] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 28},
												[5] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 29},
												[6] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 17}
										},
										["Lv"] = 2,
										["appreciation"] = {
												[1] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 6},
												[2] = {["Parameter2"] = 0,["Parameter1"] = 2,["Type"] = 7},
												[3] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 8},
												[4] = {["Parameter2"] = 0,["Parameter1"] = 2,["Type"] = 9},
												[5] = {["Parameter2"] = 0,["Parameter1"] = 2,["Type"] = 10},
												[6] = {["Parameter2"] = 0,["Parameter1"] = 5,["Type"] = 26},
												[7] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 11},
												[8] = {["Parameter2"] = 0,["Parameter1"] = 10,["Type"] = 12},
												[9] = {["Parameter2"] = 0,["Parameter1"] = 2,["Type"] = 22},
												[10] = {["Parameter2"] = 0,["Parameter1"] = 7,["Type"] = 14},
												[11] = {["Parameter2"] = 0,["Parameter1"] = 7,["Type"] = 30},
												[12] = {["Parameter2"] = 0,["Parameter1"] = 7,["Type"] = 27}
										}},
								[4] = {["function"] = {
												[1] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 13},
												[2] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 16},
												[3] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 19},
												[4] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 28},
												[5] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 29},
												[6] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 17}
										},
										["Lv"] = 3,
										["appreciation"] = {
												[1] = {["Parameter2"] = 0,["Parameter1"] = 2,["Type"] = 6},
												[2] = {["Parameter2"] = 0,["Parameter1"] = 2,["Type"] = 7},
												[3] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 8},
												[4] = {["Parameter2"] = 0,["Parameter1"] = 2,["Type"] = 9},
												[5] = {["Parameter2"] = 0,["Parameter1"] = 3,["Type"] = 10},
												[6] = {["Parameter2"] = 0,["Parameter1"] = 7,["Type"] = 26},
												[7] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 11},
												[8] = {["Parameter2"] = 0,["Parameter1"] = 15,["Type"] = 12},
												[9] = {["Parameter2"] = 0,["Parameter1"] = 3,["Type"] = 22},
												[10] = {["Parameter2"] = 0,["Parameter1"] = 8,["Type"] = 14},
												[11] = {["Parameter2"] = 0,["Parameter1"] = 8,["Type"] = 30},
												[12] = {["Parameter2"] = 0,["Parameter1"] = 8,["Type"] = 27}
										}},
								[5] = {["function"] = {
												[1] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 13},
												[2] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 16},
												[3] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 19},
												[4] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 28},
												[5] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 29},
												[6] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 17}
										},
										["Lv"] = 4,
										["appreciation"] = {
												[1] = {["Parameter2"] = 0,["Parameter1"] = 2,["Type"] = 6},
												[2] = {["Parameter2"] = 0,["Parameter1"] = 2,["Type"] = 7},
												[3] = {["Parameter2"] = 0,["Parameter1"] = 2,["Type"] = 8},
												[4] = {["Parameter2"] = 0,["Parameter1"] = 2,["Type"] = 9},
												[5] = {["Parameter2"] = 0,["Parameter1"] = 4,["Type"] = 10},
												[6] = {["Parameter2"] = 0,["Parameter1"] = 9,["Type"] = 26},
												[7] = {["Parameter2"] = 0,["Parameter1"] = 8,["Type"] = 11},
												[8] = {["Parameter2"] = 0,["Parameter1"] = 20,["Type"] = 12},
												[9] = {["Parameter2"] = 0,["Parameter1"] = 4,["Type"] = 22},
												[10] = {["Parameter2"] = 0,["Parameter1"] = 9,["Type"] = 14},
												[11] = {["Parameter2"] = 0,["Parameter1"] = 9,["Type"] = 30},
												[12] = {["Parameter2"] = 0,["Parameter1"] = 9,["Type"] = 27}
										}},
								[6] = {["function"] = {
												[1] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 13},
												[2] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 16},
												[3] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 19},
												[4] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 28},
												[5] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 24},
												[6] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 29},
												[7] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 17}
										},
										["Lv"] = 5,
										["appreciation"] = {
												[1] = {["Parameter2"] = 0,["Parameter1"] = 2,["Type"] = 6},
												[2] = {["Parameter2"] = 0,["Parameter1"] = 2,["Type"] = 7},
												[3] = {["Parameter2"] = 0,["Parameter1"] = 2,["Type"] = 8},
												[4] = {["Parameter2"] = 0,["Parameter1"] = 3,["Type"] = 9},
												[5] = {["Parameter2"] = 0,["Parameter1"] = 5,["Type"] = 10},
												[6] = {["Parameter2"] = 0,["Parameter1"] = 11,["Type"] = 26},
												[7] = {["Parameter2"] = 0,["Parameter1"] = 8,["Type"] = 11},
												[8] = {["Parameter2"] = 0,["Parameter1"] = 25,["Type"] = 12},
												[9] = {["Parameter2"] = 0,["Parameter1"] = 10,["Type"] = 14},
												[10] = {["Parameter2"] = 0,["Parameter1"] = 10,["Type"] = 27},
												[11] = {["Parameter2"] = 0,["Parameter1"] = 10,["Type"] = 30},
												[12] = {["Parameter2"] = 0,["Parameter1"] = 5,["Type"] = 22}
										}},
								[7] = {["function"] = {
												[1] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 13},
												[2] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 16},
												[3] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 19},
												[4] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 17},
												[5] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 28},
												[6] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 24},
												[7] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 29},
												[8] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 18}
										},
										["Lv"] = 6,
										["appreciation"] = {
												[1] = {["Parameter2"] = 0,["Parameter1"] = 2,["Type"] = 6},
												[2] = {["Parameter2"] = 0,["Parameter1"] = 3,["Type"] = 7},
												[3] = {["Parameter2"] = 0,["Parameter1"] = 2,["Type"] = 8},
												[4] = {["Parameter2"] = 0,["Parameter1"] = 3,["Type"] = 9},
												[5] = {["Parameter2"] = 0,["Parameter1"] = 13,["Type"] = 10},
												[6] = {["Parameter2"] = 0,["Parameter1"] = 6,["Type"] = 26},
												[7] = {["Parameter2"] = 0,["Parameter1"] = 8,["Type"] = 11},
												[8] = {["Parameter2"] = 0,["Parameter1"] = 30,["Type"] = 12},
												[9] = {["Parameter2"] = 0,["Parameter1"] = 11,["Type"] = 14},
												[10] = {["Parameter2"] = 0,["Parameter1"] = 11,["Type"] = 27},
												[11] = {["Parameter2"] = 0,["Parameter1"] = 11,["Type"] = 30},
												[12] = {["Parameter2"] = 0,["Parameter1"] = 6,["Type"] = 22}
										}},
								[8] = {["function"] = {
												[1] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 13},
												[2] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 16},
												[3] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 19},
												[4] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 17},
												[5] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 28},
												[6] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 24},
												[7] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 29},
												[8] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 18}
										},
										["Lv"] = 7,
										["appreciation"] = {
												[1] = {["Parameter2"] = 0,["Parameter1"] = 3,["Type"] = 6},
												[2] = {["Parameter2"] = 0,["Parameter1"] = 3,["Type"] = 7},
												[3] = {["Parameter2"] = 0,["Parameter1"] = 2,["Type"] = 8},
												[4] = {["Parameter2"] = 0,["Parameter1"] = 3,["Type"] = 9},
												[5] = {["Parameter2"] = 0,["Parameter1"] = 7,["Type"] = 10},
												[6] = {["Parameter2"] = 0,["Parameter1"] = 15,["Type"] = 26},
												[7] = {["Parameter2"] = 0,["Parameter1"] = 11,["Type"] = 11},
												[8] = {["Parameter2"] = 0,["Parameter1"] = 35,["Type"] = 12},
												[9] = {["Parameter2"] = 0,["Parameter1"] = 12,["Type"] = 14},
												[10] = {["Parameter2"] = 0,["Parameter1"] = 12,["Type"] = 27},
												[11] = {["Parameter2"] = 0,["Parameter1"] = 12,["Type"] = 30},
												[12] = {["Parameter2"] = 0,["Parameter1"] = 7,["Type"] = 22}
										}},
								[9] = {["function"] = {
												[1] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 13},
												[2] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 16},
												[3] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 19},
												[4] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 17},
												[5] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 18},
												[6] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 28},
												[7] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 29},
												[8] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 24}
										},
										["Lv"] = 8,
										["appreciation"] = {
												[1] = {["Parameter2"] = 0,["Parameter1"] = 3,["Type"] = 6},
												[2] = {["Parameter2"] = 0,["Parameter1"] = 3,["Type"] = 7},
												[3] = {["Parameter2"] = 0,["Parameter1"] = 3,["Type"] = 8},
												[4] = {["Parameter2"] = 0,["Parameter1"] = 3,["Type"] = 9},
												[5] = {["Parameter2"] = 0,["Parameter1"] = 8,["Type"] = 10},
												[6] = {["Parameter2"] = 0,["Parameter1"] = 17,["Type"] = 26},
												[7] = {["Parameter2"] = 0,["Parameter1"] = 11,["Type"] = 11},
												[8] = {["Parameter2"] = 0,["Parameter1"] = 40,["Type"] = 12},
												[9] = {["Parameter2"] = 0,["Parameter1"] = 13,["Type"] = 14},
												[10] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 20},
												[11] = {["Parameter2"] = 0,["Parameter1"] = 13,["Type"] = 27},
												[12] = {["Parameter2"] = 0,["Parameter1"] = 13,["Type"] = 30},
												[13] = {["Parameter2"] = 0,["Parameter1"] = 8,["Type"] = 22}
										}},
								[10] = {["function"] = {
												[1] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 13},
												[2] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 16},
												[3] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 19},
												[4] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 17},
												[5] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 18},
												[6] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 28},
												[7] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 29},
												[8] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 24}
										},
										["Lv"] = 9,
										["appreciation"] = {
												[1] = {["Parameter2"] = 0,["Parameter1"] = 3,["Type"] = 6},
												[2] = {["Parameter2"] = 0,["Parameter1"] = 3,["Type"] = 7},
												[3] = {["Parameter2"] = 0,["Parameter1"] = 3,["Type"] = 8},
												[4] = {["Parameter2"] = 0,["Parameter1"] = 4,["Type"] = 9},
												[5] = {["Parameter2"] = 0,["Parameter1"] = 9,["Type"] = 10},
												[6] = {["Parameter2"] = 0,["Parameter1"] = 19,["Type"] = 26},
												[7] = {["Parameter2"] = 0,["Parameter1"] = 11,["Type"] = 11},
												[8] = {["Parameter2"] = 0,["Parameter1"] = 45,["Type"] = 12},
												[9] = {["Parameter2"] = 0,["Parameter1"] = 14,["Type"] = 14},
												[10] = {["Parameter2"] = 0,["Parameter1"] = 14,["Type"] = 27},
												[11] = {["Parameter2"] = 0,["Parameter1"] = 14,["Type"] = 30},
												[12] = {["Parameter2"] = 0,["Parameter1"] = 9,["Type"] = 22}
										}},
								[11] = {["function"] = {
												[1] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 13},
												[2] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 16},
												[3] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 19},
												[4] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 17},
												[5] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 18},
												[6] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 28},
												[7] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 29},
												[8] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 24}
										},
										["Lv"] = 10,
										["appreciation"] = {
												[1] = {["Parameter2"] = 0,["Parameter1"] = 3,["Type"] = 6},
												[2] = {["Parameter2"] = 0,["Parameter1"] = 4,["Type"] = 7},
												[3] = {["Parameter2"] = 0,["Parameter1"] = 3,["Type"] = 8},
												[4] = {["Parameter2"] = 0,["Parameter1"] = 4,["Type"] = 9},
												[5] = {["Parameter2"] = 0,["Parameter1"] = 10,["Type"] = 10},
												[6] = {["Parameter2"] = 0,["Parameter1"] = 21,["Type"] = 26},
												[7] = {["Parameter2"] = 0,["Parameter1"] = 14,["Type"] = 11},
												[8] = {["Parameter2"] = 0,["Parameter1"] = 55,["Type"] = 12},
												[9] = {["Parameter2"] = 0,["Parameter1"] = 15,["Type"] = 14},
												[10] = {["Parameter2"] = 0,["Parameter1"] = 15,["Type"] = 27},
												[11] = {["Parameter2"] = 0,["Parameter1"] = 15,["Type"] = 30},
												[12] = {["Parameter2"] = 0,["Parameter1"] = 10,["Type"] = 22}
										}},
								[12] = {["function"] = {
												[1] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 13},
												[2] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 16},
												[3] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 19},
												[4] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 17},
												[5] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 18},
												[6] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 28},
												[7] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 29},
												[8] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 24}
										},
										["Lv"] = 11,
										["appreciation"] = {
												[1] = {["Parameter2"] = 0,["Parameter1"] = 4,["Type"] = 6},
												[2] = {["Parameter2"] = 0,["Parameter1"] = 4,["Type"] = 7},
												[3] = {["Parameter2"] = 0,["Parameter1"] = 3,["Type"] = 8},
												[4] = {["Parameter2"] = 0,["Parameter1"] = 4,["Type"] = 9},
												[5] = {["Parameter2"] = 0,["Parameter1"] = 11,["Type"] = 10},
												[6] = {["Parameter2"] = 0,["Parameter1"] = 23,["Type"] = 26},
												[7] = {["Parameter2"] = 0,["Parameter1"] = 14,["Type"] = 11},
												[8] = {["Parameter2"] = 0,["Parameter1"] = 65,["Type"] = 12},
												[9] = {["Parameter2"] = 0,["Parameter1"] = 16,["Type"] = 14},
												[10] = {["Parameter2"] = 0,["Parameter1"] = 16,["Type"] = 27},
												[11] = {["Parameter2"] = 0,["Parameter1"] = 16,["Type"] = 30},
												[12] = {["Parameter2"] = 0,["Parameter1"] = 11,["Type"] = 22}
										}},
								[13] = {["function"] = {
												[1] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 13},
												[2] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 16},
												[3] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 17},
												[4] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 18},
												[5] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 19},
												[6] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 28},
												[7] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 29},
												[8] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 24}
										},
										["Lv"] = 12,
										["appreciation"] = {
												[1] = {["Parameter2"] = 0,["Parameter1"] = 4,["Type"] = 6},
												[2] = {["Parameter2"] = 0,["Parameter1"] = 4,["Type"] = 7},
												[3] = {["Parameter2"] = 0,["Parameter1"] = 4,["Type"] = 8},
												[4] = {["Parameter2"] = 0,["Parameter1"] = 4,["Type"] = 9},
												[5] = {["Parameter2"] = 0,["Parameter1"] = 12,["Type"] = 10},
												[6] = {["Parameter2"] = 0,["Parameter1"] = 25,["Type"] = 26},
												[7] = {["Parameter2"] = 0,["Parameter1"] = 17,["Type"] = 11},
												[8] = {["Parameter2"] = 0,["Parameter1"] = 75,["Type"] = 12},
												[9] = {["Parameter2"] = 0,["Parameter1"] = 17,["Type"] = 14},
												[10] = {["Parameter2"] = 0,["Parameter1"] = 17,["Type"] = 27},
												[11] = {["Parameter2"] = 0,["Parameter1"] = 17,["Type"] = 30},
												[12] = {["Parameter2"] = 0,["Parameter1"] = 12,["Type"] = 22}
										}},
								[14] = {["function"] = {
												[1] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 13},
												[2] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 16},
												[3] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 19},
												[4] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 17},
												[5] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 18},
												[6] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 28},
												[7] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 29},
												[8] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 24}
										},
										["Lv"] = 13,
										["appreciation"] = {
												[1] = {["Parameter2"] = 0,["Parameter1"] = 4,["Type"] = 6},
												[2] = {["Parameter2"] = 0,["Parameter1"] = 4,["Type"] = 7},
												[3] = {["Parameter2"] = 0,["Parameter1"] = 4,["Type"] = 8},
												[4] = {["Parameter2"] = 0,["Parameter1"] = 4,["Type"] = 9},
												[5] = {["Parameter2"] = 0,["Parameter1"] = 13,["Type"] = 10},
												[6] = {["Parameter2"] = 0,["Parameter1"] = 27,["Type"] = 26},
												[7] = {["Parameter2"] = 0,["Parameter1"] = 20,["Type"] = 11},
												[8] = {["Parameter2"] = 0,["Parameter1"] = 85,["Type"] = 12},
												[9] = {["Parameter2"] = 0,["Parameter1"] = 18,["Type"] = 14},
												[10] = {["Parameter2"] = 0,["Parameter1"] = 18,["Type"] = 27},
												[11] = {["Parameter2"] = 0,["Parameter1"] = 18,["Type"] = 30},
												[12] = {["Parameter2"] = 0,["Parameter1"] = 13,["Type"] = 22}
										}},
								[15] = {["function"] = {
												[1] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 13},
												[2] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 16},
												[3] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 19},
												[4] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 17},
												[5] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 18},
												[6] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 28},
												[7] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 29},
												[8] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 24}
										},
										["Lv"] = 14,
										["appreciation"] = {
												[1] = {["Parameter2"] = 0,["Parameter1"] = 4,["Type"] = 6},
												[2] = {["Parameter2"] = 0,["Parameter1"] = 4,["Type"] = 7},
												[3] = {["Parameter2"] = 0,["Parameter1"] = 4,["Type"] = 8},
												[4] = {["Parameter2"] = 0,["Parameter1"] = 4,["Type"] = 9},
												[5] = {["Parameter2"] = 0,["Parameter1"] = 14,["Type"] = 10},
												[6] = {["Parameter2"] = 0,["Parameter1"] = 29,["Type"] = 26},
												[7] = {["Parameter2"] = 0,["Parameter1"] = 23,["Type"] = 11},
												[8] = {["Parameter2"] = 0,["Parameter1"] = 95,["Type"] = 12},
												[9] = {["Parameter2"] = 0,["Parameter1"] = 19,["Type"] = 14},
												[10] = {["Parameter2"] = 0,["Parameter1"] = 19,["Type"] = 27},
												[11] = {["Parameter2"] = 0,["Parameter1"] = 14,["Type"] = 22},
												[12] = {["Parameter2"] = 0,["Parameter1"] = 19,["Type"] = 30}
										}},
								[16] = {["function"] = {
												[1] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 13},
												[2] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 16},
												[3] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 19},
												[4] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 17},
												[5] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 18},
												[6] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 28},
												[7] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 29},
												[8] = {["Parameter2"] = 0,["Parameter1"] = 1,["Type"] = 24}
										},
										["Lv"] = 15,
										["appreciation"] = {
												[1] = {["Parameter2"] = 0,["Parameter1"] = 4,["Type"] = 6},
												[2] = {["Parameter2"] = 0,["Parameter1"] = 4,["Type"] = 7},
												[3] = {["Parameter2"] = 0,["Parameter1"] = 4,["Type"] = 8},
												[4] = {["Parameter2"] = 0,["Parameter1"] = 4,["Type"] = 9},
												[5] = {["Parameter2"] = 0,["Parameter1"] = 15,["Type"] = 10},
												[6] = {["Parameter2"] = 0,["Parameter1"] = 31,["Type"] = 26},
												[7] = {["Parameter2"] = 0,["Parameter1"] = 26,["Type"] = 11},
												[8] = {["Parameter2"] = 0,["Parameter1"] = 105,["Type"] = 12},
												[9] = {["Parameter2"] = 0,["Parameter1"] = 20,["Type"] = 14},
												[10] = {["Parameter2"] = 0,["Parameter1"] = 15,["Type"] = 22},
												[11] = {["Parameter2"] = 0,["Parameter1"] = 20,["Type"] = 27},
												[12] = {["Parameter2"] = 0,["Parameter1"] = 20,["Type"] = 30},
												[13] = {["Parameter2"] = 20,["Parameter1"] = 202403,["Type"] = 25}
										}}
						}}}
}
return VipConfig